name: base
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - bokeh=1.3.4
  - hvplot=0.5.2
  - jupyter-panel-proxy
  - jupyter-server-proxy
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - numpy=1.17.2
  - pandas=0.25.1
  - panel=0.6.4
  - python=3.7.4
  - scipy=1.3.1
  - jupyter=1.0.0


